name = "backend"
compatibility_date = "2023-12-01"

[vars]
# Connection Pool URL
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiOGNiNjdlMDUtZWNhZi00ZjMzLThmYjMtNGZiZDlmNGIwZTFmIiwidGVuYW50X2lkIjoiNDhjM2EzNzVjMjMxYjI0ODcxZTUwOGY1ZmVkNTRmZDlmOWZhNzU0M2NjNTJkYjU2ZGMwNmIyNTJhMTI3NjNhYSIsImludGVybmFsX3NlY3JldCI6ImQ0ZTc0MDMxLThlODctNDM5ZC04Zjg5LTFiZjk2ZTA4MzViNCJ9.c6LKolZQvxOoSz2IS7WCKq15a928sCThpFD7k2FqStw"
JWT_SECRET="secret"
